# 官方文档
# https://squidfunk.github.io/mkdocs-material/

site_name: Orionxer's Note
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default # 浅色模式
      toggle:
        icon: material/brightness-7 
        name: 切换深色模式
      primary: teal   # 主题颜色
      accent: green
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换浅色模式
      primary: teal   # 主题颜色
      accent: green
  #  favicon: attachment/portrait.png
  language: zh # 中文，解决中文搜索问题
  features:
    - navigation.expand 
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.tabs
    # - navigation.tabs.sticky # 固定显示顶部栏
    - navigation.indexes
    # - navigation.footer
    - navigation.path
    - navigation.sections
    - content.code.copy # 代码复制按钮
    - content.footnote.tooltips # 脚注提示
markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break 
  - toc:
      permalink: false
  - admonition
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true  # 启用 MathJax
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true // 是否可选
extra_javascript: # 显示公式js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - roamlinks 
    # - autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
        
# copyright: Creative Commons BY SA 4.0
# extra:
#   social:
#     - icon: fontawesome/brands/github 
#       link: https://github.com/Orionxer
#       name: Orionxer's github
