# 官方文档
# https://squidfunk.github.io/mkdocs-material/

site_name: Orionxer's Note
site_url: https://orionxer.github.io/foam
# nav: # 自定义导航栏
#   - Home: index.md
#   - About: todo.md
#   - Gettting Started: 
#     - getting-started/creating-new-notes.md
# repo_url: https://github.com/squidfunk/mkdocs-material # 添加github仓库信息
# repo_name: squidfunk/mkdocs-material
theme:
  name: material
  # logo: images/favicon.png # 待更新为自定义的主页Logo
  palette:
    # Palette toggle for light mode
    - scheme: default # 浅色模式
      toggle:
        icon: material/weather-night
        name: 切换深色模式
      primary: teal   # 主题颜色
      accent: green
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换浅色模式
      primary: teal   # 主题颜色
      accent: green
  #  favicon: attachment/portrait.png
  language: zh
  features:
    - navigation.expand 
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.tabs
    # - navigation.tabs.sticky # 固定显示顶部栏
    - navigation.indexes
    # - navigation.footer
    - navigation.path
    - navigation.sections
    - content.code.copy # 代码复制按钮
    - content.footnote.tooltips # 脚注提示
markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break 
  - toc:
      permalink: false
  - admonition
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true  # 启用 MathJax
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true // 是否可选
extra_javascript: # 显示数学公式js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - tags:         # material主题自带，其他主题可能需要注释tags功能
      enabled: true
      tags: false # 是否在文章顶部显示标签
  - search:
      jieba_dict: dict.txt  # 强化中文搜索
  - roamlinks 
    # - autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
        
# copyright: Creative Commons BY SA 4.0
# extra:
#   social:
#     - icon: fontawesome/brands/github 
#       link: https://github.com/Orionxer
#       name: Orionxer's github
