name: ci
on:
  push:
    branches:
      - master
      - mkdocs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-exclude
      - run: pip install mkdocs-roamlinks-plugin
      - run: mkdocs gh-deploy --force
  

