name: ci
on:
  push:
    branches:
      - master
      - mkdocs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      # Setup Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      # Install all required packages in one step
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装requirements.txt中的依赖
      # Deploy to GitHub Pages
      - run: mkdocs gh-deploy --force
